In [3]:
import numpy as np
import pandas as pd
import csv
import os
import matplotlib.pylab as plt


from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import classification_report
import sklearn.metrics

from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier

from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

from sklearn import metrics


In [4]:
#load the data
data = pd.read_csv("iris.csv")
data.head(10)

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
7  4.4  2.9  1.4  0.2  Iris-setosa
8  4.9  3.1  1.5  0.1  Iris-setosa
9  5.4  3.7  1.5  0.2  Iris-setosa

In [5]:
data.shape
data.describe()

5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [6]:


x = data.iloc[:,0:4].values
y = data.iloc[:,4].values

In [7]:
data_list = list(data.columns)

In [8]:
#Divide data into training and test set
from sklearn.model_selection import train_test_split

X_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state = 0)

In [11]:
#Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
x_test = sc_X.transform(x_test)


In [12]:
#Train the model
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, random_state = 0)
classifier.fit(X_train,y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [13]:
#Prediction 
Y_Pred = classifier.predict(x_test)

In [14]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
Cm = confusion_matrix(y_test, Y_Pred)
As = accuracy_score(y_test, Y_Pred)
Cr = classification_report(y_test, Y_Pred)
print(Cm)
print(As)
print(Cr)

[[12  0  0]
 [ 0 10  0]
 [ 0  3  5]]
0.9
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.77      1.00      0.87        10
 Iris-virginica       1.00      0.62      0.77         8

      micro avg       0.90      0.90      0.90        30
      macro avg       0.92      0.88      0.88        30
   weighted avg       0.92      0.90      0.89        30



In [15]:
#errors
errors = abs(Y_Pred - y_test)
#  mean absolute error 
print('Mean Absolute Error:', round(np.mean(errors), 2))

TypeError: unsupported operand type(s) for -: 'str' and 'str'